# Generated by Django 4.2.11 on 2024-06-07 08:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcnqsd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folderfilemodel',
            name='file_name',
        ),
        migrations.AddField(
            model_name='folderfilemodel',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='upload/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='fieldlabelmodel',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gcnqsd.folderfilemodel'),
        ),
    ]
